---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgCtqjvu65OqJ2m3NptKtTyHrSMQq0/FFdslhBkIhc3uZZ0IJ4E6CBkqmzQ+7cGDieUUPQWwXBMJ7Bou01S0lI+QDECG2fw8I1k/D9JmW5EJOTNBd4gTOnbA5w8/U6TbsImkPSwg+cnNdzyUkSY88mTYyMC3VOoH3NSNuNiLjyRHXM/EV7QmkmKysh7N23NQ/rWaKexMEgmIZlLH0osK3cTgbpEFmn4dy+N0ljnOoAYmU3aCZFWJw44PYfyfU5P/DxB3NVKKMCGhjdO/ftXorSmuZeZ8LLNRWgajuzlWydMxT1ZLpZoC1VXiPWhZGM0Ew4ZjZJEoZl1XUJEu6XvFEIn52944jf/cw0RXFUB9pQ1L/X6NlJiVT1w8XSvuSaiVu23FLRvDvJyTf+PruOpbCNO50rbUFAOF5lQYePvaWoEkwb8fK44uzu/MMFOYLmRpzNN5MtIhnMQk6DIr9lEGtoNW2L4IpTgjCWcM3Pl6M9CwXgsq+CKo/+K3Iy/B/cfk1NcofUqn/5jpvkrqq6hnGdXhWhshS5IEJLyWCFrdkVRPBFHSCLJlnGXu08Xt0yIueQUZHKS/DeLgOjeD1H0sECetrlesrU0i2h2d0Uj8t0iIrisW7ZNOJq3iuZ+GQEeKJkqkrM5jQMGg1a4CkZZZgCvzWi4YGEzdRL8ZMR3+ArT1jHvgLqwJ1/6joIjbBSBr9cOKbbgcGcRNsu0DxWMn0rBAxPj/194gcw==
  template:
    metadata:
      name: db-credentials
      namespace: default
